name: Japanese Kana
favicon: null
layout_spectrum: 0.4837775242049247
typography_spectrum: 0.35607533319853246
title: Japan Betting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161417'
    - '#353535'
    - '#fefefe'
    - '#667280'
    - '#c1c2c4'
  brandStrength: 0.5
  lightness: 0.12566672475077212
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
