name: Japanese Kana
favicon: null
layout_spectrum: 0.24958
typography_spectrum: 0.35607533319853246
title: Japan Betting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f6739'
    - '#000000'
    - '#d7d8d0'
    - '#b2b6b9'
  brandStrength: 0.5
  lightness: 0.12566672475077212
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
